#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout


signup:
    path: /signup
    controller: App\Controller\UserController::signup

signin:
    path: /signin
    controller: App\Controller\UserController::signin

